backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'src/pages/learn/index.md'
        label: 'Learn'
        name: 'learn'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'learn-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'src/pages/listen/index.md'
        label: 'Listen'
        name: 'listen'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'listen-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
              label: 'Apple Music URL',
              name: 'appleMusicUrl',
              widget: 'string',
            }
          - { label: 'Spotify URL', name: 'spotifyUrl', widget: 'string' }
          - { label: 'Soundcloud URL', name: 'soundcloudUrl', widget: 'string' }
          - { label: 'Youtube URL', name: 'youtubeUrl', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'src/pages/look/index.md'
        label: 'Look'
        name: 'look'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'look-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
              label: Gallery,
              name: gallery,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Alt Text, name: altText, widget: string },
                ],
            }
      - file: 'src/pages/live/index.md'
        label: 'Live'
        name: 'live'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'live-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
              label: Upcoming Shows,
              name: shows,
              widget: list,
              fields:
                [
                  { label: Venue, name: venue, widget: string },
                  { label: City + State, name: cityState, widget: string },
                  { label: Date, name: date, widget: string },
                  {
                    label: Buttons,
                    name: buttons,
                    widget: list,
                    fields:
                      [
                        { label: Text, name: text, widget: string },
                        { label: URL, name: url, widget: string },
                      ],
                  },
                ],
            }
